project:
  type: website

website:
  title: "Statistical Computing (BSPH 140.776)"
  site-url: https://lcolladotor.github.io/jhustatcomputing2023
  description: "Course website for Statistical Computing (BSPH 140.776) in Fall 2023"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "General Information"
        menu:
        - text: "Syllabus"
          href: syllabus.qmd
        - text: "Schedule"
          href: schedule.qmd
      - text: "Course Materials"
        menu: 
        - text: "Lectures"
          href: lectures.qmd
        - text: "Projects"
          href: projects.qmd
        - text: "Resources"
          href: resources.qmd
      - icon: github
        href: https://github.com/lcolladotor/jhustatcomputing2023
      - icon: twitter
        href: https://twitter.com/lcolladotor
      - icon: rss
        href: index.xml
format:
  html:
    theme: simplex
    toc: true
    css: styles.css

editor: visual

execute:
  freeze: auto
